version: "3.6"
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    restart: always
    command: >
      --requirepass redispassword
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management console port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  rabbitmq_data:
