"""added pid col

Revision ID: 29922f54adab
Revises: b093af3a5cfd
Create Date: 2023-08-25 09:35:55.172449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29922f54adab'
down_revision = 'b093af3a5cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_data', sa.Column('pid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_data', 'pid')
    # ### end Alembic commands ###