"""added validation instance model

Revision ID: 66386b7103a4
Revises: 3816bb6c2a91
Create Date: 2023-10-10 16:59:43.644446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66386b7103a4'
down_revision = '3816bb6c2a91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('enqueue_time', sa.BigInteger(), nullable=True))
    op.add_column('validation_instance', sa.Column('schema_pull_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_instance', 'schema_pull_time')
    op.drop_column('validation_instance', 'enqueue_time')
    # ### end Alembic commands ###