"""added validation instance model

Revision ID: 928f37155aab
Revises: 253e6cdeaa39
Create Date: 2023-10-09 00:53:04.116447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928f37155aab'
down_revision = '253e6cdeaa39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###