"""edted validation tbale

Revision ID: ce0b3036a783
Revises: ed84b4f2b1b1
Create Date: 2023-08-18 10:10:29.522144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b3036a783'
down_revision = 'ed84b4f2b1b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation', 'row')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation', sa.Column('row', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###