"""added validation instance model

Revision ID: 0792aa0a2c68
Revises: aa73a8b9baaf
Create Date: 2023-10-10 20:13:22.331346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0792aa0a2c68'
down_revision = 'aa73a8b9baaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_instance', 'pid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('validation_instance_pid_key', 'validation_instance', type_='unique')
    op.drop_column('validation_instance', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('validation_instance_pid_key', 'validation_instance', ['pid'])
    op.alter_column('validation_instance', 'pid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###