"""added new

Revision ID: 2406496bb60a
Revises: 9278458a9c5c
Create Date: 2023-08-19 12:06:01.843319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2406496bb60a'
down_revision = '9278458a9c5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_data', sa.Column('data_id', sa.BigInteger(), nullable=False))
    op.add_column('validation_data', sa.Column('created_at', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'validation_data', 'uploads', ['data_id'], ['id'])
    op.drop_column('validation_data', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_data', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'validation_data', type_='foreignkey')
    op.drop_column('validation_data', 'created_at')
    op.drop_column('validation_data', 'data_id')
    # ### end Alembic commands ###