"""added validation instance model

Revision ID: 3816bb6c2a91
Revises: 0dd3a3faf74f
Create Date: 2023-10-10 16:52:47.751999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3816bb6c2a91'
down_revision = '0dd3a3faf74f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('validation_start_time', sa.BigInteger(), nullable=True))
    op.add_column('validation_instance', sa.Column('validation_end_time', sa.BigInteger(), nullable=True))
    op.add_column('validation_instance', sa.Column('org_id', sa.Integer(), nullable=True))
    op.drop_constraint('validation_instance_organization_id_fkey', 'validation_instance', type_='foreignkey')
    op.create_foreign_key(None, 'validation_instance', 'organizations', ['org_id'], ['id'])
    op.drop_column('validation_instance', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'validation_instance', type_='foreignkey')
    op.create_foreign_key('validation_instance_organization_id_fkey', 'validation_instance', 'organizations', ['organization_id'], ['id'])
    op.drop_column('validation_instance', 'org_id')
    op.drop_column('validation_instance', 'validation_end_time')
    op.drop_column('validation_instance', 'validation_start_time')
    # ### end Alembic commands ###