"""added validation instance model

Revision ID: 75196342676f
Revises: 0792aa0a2c68
Create Date: 2023-10-10 20:17:18.821638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75196342676f'
down_revision = '0792aa0a2c68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('validation_instance', 'pid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_instance', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('validation_instance', 'id')
    # ### end Alembic commands ###