"""added schema table

Revision ID: 9278458a9c5c
Revises: a1ecf81a6fd0
Create Date: 2023-08-18 14:49:14.196720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9278458a9c5c'
down_revision = 'a1ecf81a6fd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('validation_data', sa.Column('schema_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'validation_data', 'schema_data', ['schema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_data', type_='foreignkey')
    op.drop_column('validation_data', 'schema_id')
    op.drop_table('schema_data')
    # ### end Alembic commands ###