"""edted validation tbale

Revision ID: a1ecf81a6fd0
Revises: ce0b3036a783
Create Date: 2023-08-18 10:20:55.644374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ecf81a6fd0'
down_revision = 'ce0b3036a783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('validation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploads.id'], name='validation_file_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='validation_pkey')
    )
    op.drop_table('validation_data')
    # ### end Alembic commands ###