"""added validation instance model

Revision ID: aa73a8b9baaf
Revises: 8acf99155da7
Create Date: 2023-10-10 20:06:01.754172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa73a8b9baaf'
down_revision = '8acf99155da7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###