"""added new cols

Revision ID: b093af3a5cfd
Revises: 2406496bb60a
Create Date: 2023-08-21 11:31:20.458370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b093af3a5cfd'
down_revision = '2406496bb60a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_data', sa.Column('created_at', sa.BigInteger(), nullable=False))
    op.add_column('schema_data', sa.Column('org_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'schema_data', 'organizations', ['org_id'], ['id'])
    op.add_column('validation_data', sa.Column('org_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'validation_data', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_data', type_='foreignkey')
    op.drop_column('validation_data', 'org_id')
    op.drop_constraint(None, 'schema_data', type_='foreignkey')
    op.drop_column('schema_data', 'org_id')
    op.drop_column('schema_data', 'created_at')
    # ### end Alembic commands ###