"""added validation table

Revision ID: ed84b4f2b1b1
Revises: 0aeb3276039b
Create Date: 2023-08-17 22:47:48.450615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed84b4f2b1b1'
down_revision = '0aeb3276039b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('row', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation')
    # ### end Alembic commands ###